### PR TITLE
Error when relaxed parameter mean or sd is infinite

### PR DESCRIPTION
**Pull request by joshwlambert**
This PR addresses #159. It stops the DAISIE relaxed-rate MLE model when an infinite value for the mean or standard deviation is detected and returns an error message to the user. 

See #159 for discussion on why infinite values for these parameters shouldn't be allowed.

⚠️ I have not tested this locally due to not being able to currently compile the package. Please review this PR carefully before merging to check for unintended side-effects. However, this change should be isolated to only the relaxed-rate model as the change is in `DAISIE_loglik_integrate()`.

As this change is minor, I do not this a release is required after merging this change, however, I do not have a strong opinion on this, and a patch release could also be warranted.

### CODE REVIEW

**Comment by Neves-P** [comment]
lgtm, I'd be up for a minor release if we bundle this with the shiftloglik changes (and maybe a pkgdown page, up to you all)

**Review by Neves-P — APPROVED** [review]

**Comment by Neves-P** [comment]
As this merge is going to master @rsetienne need to be the one to merge it.

**Comment by joshwlambert** [comment]
Thanks for reviewing @Neves-P. 

After discussing the change with Rampal, he suggested merging the change into develop before then merging develop into master afterwards. I've redirected this pull request to the `develop` branch.

**Comment by Neves-P** [comment]
Sounds good!

**Pull request merged**
