### PR TITLE
v4.4.1

### PR DESCRIPTION
**Pull request by Neves-P**
# DAISIE 4.4.1

* Fix bug in the calculation of shift loglikelihoods.
* Fix bug where parameters being optimized could incorrectly be `Inf` #159 #160 (@joshwlambert).
* `DAISIE_SR_loglik_CS_M1()` is now `DAISIE_loglik_CS_shift()`.
* New pkgdown website.
* Several improvements to the relaxed rate code.

### CODE REVIEW

**Comment by Neves-P** [comment]
@joshwlambert @rsetienne , could you please take a quick look at the `NEWS.md` and see if I'm forgetting anything? The text is the same as the first comment of this PR.

**Comment by joshwlambert** [comment]
It would be useful to link the pkgdown website in the About section on the DAISIE github repo.

**Review by joshwlambert — APPROVED** [review]
I've reviewed the changes and everything looks good to me.

There is nothing missing from the NEWS file that I could see other than extremely minor changes, e.g. explicit namespacing of tests. 

I would suggest submitting to CRAN in order to easily use the new changes when running models locally and on the cluster.

**Comment by joshwlambert** [comment]
As far as I can see the test that has the numerical discrepancy issue has now been skipped. Would it be possible to log an issue stating which test (file name and line number) is causing the issue? This can then be tackled in a follow-up PR.

**Comment by joshwlambert** [comment]
@rsetienne @Neves-P It would be great to get these changes merged and a new version of DAISIE sent to CRAN to easily install the package across different platforms.

**Comment by Neves-P** [comment]
This looks good to me, I just added a tolerance again and unskipped the test after having checked with Hanno and @rsetienne that these numerical differences are to be expected. @rsetienne , as soon as GHA are done, could you please merge or should I go ahead (there is already one review, so I can merge it).

**Pull request merged**
